apiVersion: apps/v1
kind: Deployment
metadata:
  name: todobackend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todobackend
  template:
    metadata:
      name: todobackend
      labels:
        app: todobackend
    spec:
      containers:
      - name: todobackend
        readinessProbe:
          httpGet:
            path: /hello
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 1
          failureThreshold: 1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: POSTGRES_HOST
          value: postgresdb
        image: todobackend:v0.2
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
