apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoui
  template:
    metadata:
      name: todoui
      labels:
        app: todoui
    spec:
      containers:
      - name: todoui
        image: todoui:v0.1
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
