apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoui-0-1
  labels:
    app: todoui
    version: "0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoui
      version: "0.1"
  template:
    metadata:
      name: todoui
      labels:
        app: todoui
        version: "0.1"
    spec:
      containers:
      - name: todoui
        image: novatec/technologyconsulting-containerexcerciseapp-todoui:v0.1
      restartPolicy: Always
