apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoui-0-2
  labels:
    app: todoui
    version: "0.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoui
      version: "0.2"
  template:
    metadata:
      name: todoui
      labels:
        app: todoui
        version: "0.2"
    spec:
      containers:
      - name: todoui
        image: novatec/technologyconsulting-containerexcerciseapp-todoui:v0.2
      restartPolicy: Always
